### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by candalfigomoro** [conda-forge/tensorflowonspark-feedstock#5]
Hi @afloren,

is it possible to update this package to the latest 2.2.1 version?

Thank you

**Comment by afloren** [comment]
Hey @candalfigomoro not sure went wrong during the initial setup, but I wasn't actually granted edit rights on this repo so I can't merge PRs :\

**Comment by afloren** [comment]
@conda-forge/help-python not sure who the right person to ping about this is. What's the process for adding a maintainer to an existing feedstock?

**Comment by afloren** [comment]
v2.2.1 is now available
